### ISSUE TITLE
EPIC: Create a server for a multiplayer support

### ISSUE THREAD

**Issue by Dominux** [Dominux/DGS#39]
- [x] Пользователь создает аккаунт
- [x] Пользователь создает комнату
- [x] Пользователь может получить комнату по ссылке
- [x] Пользователь создает ссылку на приглашение в комнату
- [x] Пользователь принимает ссылку на приглашение в комнату и добавляется в нее как второй игрок
- [x] Первый игрок начинает игру
- [x] Открыть WS соединение
- [x] При создании игры создавать историю
- [x] Создать сущность записи истории
- [x] Делать новые записи каждый ход
- [x] ~~При отмене хода - удалять запись~~
- [x] Добавить страницу выбора режима игры, синглплеер будет везти к существующей версии игры, мультиплеер - к новой, серверной
- [x] Запустить бэк в дев режиме
- [x] Подключить к бэку фронт
- [x] Добавить страницу регистрации
- [x] Добавить страницу комнат с возможностью ее создания
- [x] Добавить страницу комнаты по id, с видом, кто из игроков уже есть и кнопкой начала игры у черного (первого) игрока
- [x] Удалять room states когда оба игрока отключились от сокета
- [x] Зарезолвить баг с роутингом фронта на проде
- [x] Баг в синглплейре - камни ставятся, начиная с белого, а не с черного
- [x] Разворачивать бэк на сервере
- [x] Бэк по HTTPS
- [x] Проксировать трафик `wss`

**Comment by Dominux** [comment]
![image](https://user-images.githubusercontent.com/55978340/210016611-d92989ae-c0ff-4825-ba4e-0d42249e7b66.png)

**Comment by Dominux** [comment]
Dev contains that
`2023-01-18T16:57:53.706417Z  INFO request: finished processing request latency=0 ms status=101 method=GET uri=/games/ws/e089bfdb-3de1-4224-988e-ebd3bb464033 version=HTTP/1.1`
Prod doesn't

**Comment by Dominux** [comment]
PROD does:
`2023-01-18T17:41:09.690924Z  INFO request: finished processing request latency=0 ms status=400 method=GET uri=/games/ws/32d3eb14-9219-448e-b7dc-c33bab85e65c version=HTTP/1.0`

**Comment by Dominux** [comment]
It works on [the simple chat example](https://github.com/tokio-rs/axum/tree/main/examples/chat) placed in same conditions (docker container, same nginx conf and domain/subdomain)
